version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "RomiC"
    commit-message:
      prefix: "ğŸ†™ ğŸ› ï¸"
    labels:
      - "dependencies"
      - "dx"
    reviewers:
      - "RomiC"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "RomiC"
    commit-message:
      prefix: "ğŸ†™ ğŸ“¦"
    labels:
      - "dependencies"
      - "dx"
    reviewers:
      - "RomiC"
    versioning-strategy: increase